#!/bin/bash
#
# Web3 Pi Staking - Help
#

echo ""
echo "============================================================"
echo "  WEB3 PI STAKING - QUICK REFERENCE"
echo "============================================================"
echo ""
echo "  CONFIGURATION"
echo "  -----------------"
echo "  Network config file:"
echo "       /opt/web3pi/config"
echo ""
echo "  Change network (before first sync):"
echo "       sudo nano /opt/web3pi/config"
echo "       # Set NETWORK=hoodi or NETWORK=mainnet"
echo ""
echo "  FIRST TIME SETUP"
echo "  -----------------"
echo "  1. Create encrypted storage for validator keys:"
echo "       sudo /opt/web3pi/setup-luks.sh"
echo ""
echo "  INITIAL SYNC (one-time)"
echo "  -----------------"
echo "  Fast sync using checkpoint (before starting beacon node):"
echo "       sudo /opt/web3pi/trusted-node-sync.sh"
echo ""
echo "       (uses NETWORK from /opt/web3pi/config)"
echo ""
echo "  AFTER EACH REBOOT"
echo "  -----------------"
echo "  2. Unlock encrypted storage:"
echo "       sudo /opt/web3pi/unlock-luks.sh"
echo ""
echo "  3. Start the validator:"
echo "       sudo /opt/web3pi/start-validator.sh"
echo ""
echo "  SERVICE STATUS"
echo "  -----------------"
echo "  Geth (Execution Layer):"
echo "       sudo systemctl status geth"
echo "       sudo journalctl -u geth -f"
echo ""
echo "  Nimbus Beacon Node (Consensus Layer):"
echo "       sudo systemctl status nimbus-beacon-node"
echo "       sudo journalctl -u nimbus-beacon-node -f"
echo ""
echo "  Nimbus Validator:"
echo "       sudo systemctl status nimbus-validator"
echo "       sudo journalctl -u nimbus-validator -f"
echo ""
echo "  SERVICE CONTROL"
echo "  -----------------"
echo "  Start/Stop/Restart services:"
echo "       sudo systemctl start <service>"
echo "       sudo systemctl stop <service>"
echo "       sudo systemctl restart <service>"
echo ""
echo "  LOGS"
echo "  -----------------"
echo "  Web3 Pi installation log:"
echo "       cat /opt/web3pi/logs/web3pi.log"
echo ""
echo "  DATA DIRECTORIES"
echo "  -----------------"
echo "  Geth:           /var/lib/el"
echo "  Nimbus Beacon:  /var/lib/cl"
echo "  Validator Keys: /home/signer/keys (encrypted)"
echo ""
echo "  SSH SECURITY"
echo "  -----------------"
echo "  Add SSH public key:"
echo "       sudo /opt/web3pi/ssh-add-key.sh"
echo ""
echo "  Disable password login (key-only):"
echo "       sudo /opt/web3pi/ssh-disable-password.sh"
echo ""
echo "============================================================"
echo ""
